site_name: Halakasy
site_url: https://halakasy.github.io/
nav:
  - index.md
  - plane_wave.md
  - current_density.md
markdown_extensions: #https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#mkdocsyml
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.magiclink # auto-link HTML, FTP, and email links https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.keys # add keys like ++ctrl+alt+delete++ # https://facelessuser.github.io/pymdown-extensions/extensions/keys/
  - pymdownx.tabbed # add tabs https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.details # add spoiler (??? note) https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.snippets # insert a file into another markdown file https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.superfences # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - footnotes # https://python-markdown.github.io/extensions/footnotes/
  - tables # https://python-markdown.github.io/extensions/tables/
  - admonition # tips & notes (!!! note) https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - attr_list # https://python-markdown.github.io/extensions/attr_list/
  - smarty # converts ASCII dashes, quotes and ellipses to their HTML entity equivalents https://python-markdown.github.io/extensions/smarty/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: material

plugins: 
  - search
  - i18n:
      docs_structure: suffix
      default_language: ru
      languages:
        ru:
          name: Russian
          build: true
          site_name: "Halakasy"
